development:
  adapter: postgresql
  encoding: unicode
  database: review_dev
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: review_test
  pool: 5
staging:
  adapter: postgresql
  encoding: unicode
  database: review_staging
  pool: 5
smoke:
  adapter: postgresql
  encoding: unicode
  database: review_smoke
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: review_production
  pool: 5
